# Generated by Django 5.2.4 on 2025-07-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_rename_password_user_password1_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='uploads'),
        ),
    ]
