# Generated by Django 5.2.4 on 2025-07-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='uploads/anonimous.jpg', upload_to='uploads'),
        ),
    ]
