# Generated by Django 5.2.4 on 2025-07-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0011_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
