# Generated by Django 5.2.4 on 2025-07-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0012_remove_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='uploads/anonimous.jpg', upload_to='uploads'),
        ),
    ]
